# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            iNeo
tagline:          'Blog'
description:      'Blog'
url:              https://blog.ineo.vn
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
homepage:         https://ineo.vn

author:
  name:           'Hoàng Bảo Vũ'
  url:            https://facebook.com/ineo.vn
  bio:            I'm a front-end developer. I have a passion for web design and love to create for web and mobile.

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/hoangbaovu/blog.ineo.vn
